// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjxTyoqVAhpqrq79kLC5cAkcFu_v3tQU',
    appId: '1:295485105733:web:5a6f0bebe46dc19e56a52c',
    messagingSenderId: '295485105733',
    projectId: 'frosthack-c3026',
    authDomain: 'frosthack-c3026.firebaseapp.com',
    storageBucket: 'frosthack-c3026.appspot.com',
    measurementId: 'G-9Z17374371',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYUEVWVAq4mlANf42nFoDV3BboeFPX0g',
    appId: '1:295485105733:android:81ccf1979ac0150656a52c',
    messagingSenderId: '295485105733',
    projectId: 'frosthack-c3026',
    storageBucket: 'frosthack-c3026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZVNqAVwxAfn7YgpOMsMxyPGYMhKAaqY4',
    appId: '1:295485105733:ios:623021a51b68196c56a52c',
    messagingSenderId: '295485105733',
    projectId: 'frosthack-c3026',
    storageBucket: 'frosthack-c3026.appspot.com',
    iosBundleId: 'com.example.meetInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZVNqAVwxAfn7YgpOMsMxyPGYMhKAaqY4',
    appId: '1:295485105733:ios:6e6ecf65f8b5055556a52c',
    messagingSenderId: '295485105733',
    projectId: 'frosthack-c3026',
    storageBucket: 'frosthack-c3026.appspot.com',
    iosBundleId: 'com.example.meetInterface.RunnerTests',
  );
}
